"""changing start and end in sub to sub_start and sub_end

Revision ID: 195dbf46f85d
Revises: dc241dacf7d2
Create Date: 2025-01-29 12:36:08.706771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "195dbf46f85d"
down_revision: Union[str, None] = "dc241dacf7d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subscription", "start", new_column_name="sub_start")
    op.alter_column("subscription", "end", new_column_name="sub_end")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("subscription", "sub_start", new_column_name="start")
    op.alter_column("subscription", "sub_end", new_column_name="end")
    # ### end Alembic commands ###
