"""authorBook relashionship

Revision ID: 89103d332341
Revises: c9f802b063d9
Create Date: 2025-01-26 15:32:01.632945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89103d332341"
down_revision: Union[str, None] = "c9f802b063d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_genre", sa.Column("genre_id", sa.Integer(), nullable=False))
    op.drop_constraint("book_genre_gente_id_fkey", "book_genre", type_="foreignkey")
    op.create_foreign_key(
        None, "book_genre", "genre", ["genre_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("book_genre", "gente_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_genre",
        sa.Column("gente_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "book_genre", type_="foreignkey")
    op.create_foreign_key(
        "book_genre_gente_id_fkey",
        "book_genre",
        "genre",
        ["gente_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("book_genre", "genre_id")
    # ### end Alembic commands ###
