"""creating reservation queue

Revision ID: 8eee9d79f622
Revises: 6027a80a9a97
Create Date: 2025-01-30 11:46:33.817838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eee9d79f622"
down_revision: Union[str, None] = "6027a80a9a97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservation_queue",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("reservation", "price")
    op.drop_column("reservation", "is_satisfied")
    op.drop_column("reservation", "position")
    op.drop_column("reservation", "is_done")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column(
            "is_done",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "reservation",
        sa.Column(
            "position",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "reservation",
        sa.Column(
            "is_satisfied",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "reservation",
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_table("reservation_queue")
    # ### end Alembic commands ###
