"""deleted is back for reservation

Revision ID: c79c69488cfe
Revises: 8eee9d79f622
Create Date: 2025-01-30 12:03:27.374505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c79c69488cfe"
down_revision: Union[str, None] = "8eee9d79f622"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column(
            "is_ended", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservation", "is_ended")
    # ### end Alembic commands ###
